name: Build
on:
  push:
    branches:
      - master

concurrency:
  group: "cf-pages"
  cancel-in-progress: false

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@v4
      with:
        # All history is required for https://vitepress.dev/reference/default-theme-last-updated
        fetch-depth: 0
    - uses: pnpm/action-setup@v4
    - name: Prepare fonts and images
      shell: bash
      run: |
        sudo snap install typst
        curl -OL https://github.com/typst-doc-cn/guide/releases/download/files/fonts.7z
        7z x fonts.7z -ofonts
    - name: Setup and build
      shell: bash
      run: |
        pnpm install
        pnpm build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/.vitepress/dist

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: typst-doc-cn-guide
          directory: "./docs/.vitepress/dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
