name: Build
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  Vitepress_build:
    runs-on: ubuntu-latest
    name: Vitepress build
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Setup and build
      shell: bash
      run: |
        pnpm install
        pnpm build
        cd docs/.vitepress/dist
        touch .nojekyll
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git init
        git add -A
        git commit -m autobuild
        git push -f https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git master:gh-pages
